### ISSUE TITLE
Slides on your github

### ISSUE THREAD

**Issue by eliassal** [huijing/slides#14]
Hi Chen, very interesting talk I am watching about Modern CSS Layout at 
https://www.sitepoint.com/premium/tech-talks/pixel-pioneers/using-devtools-to-understand-modern-css-layouts.
I visited your github, in Firefox when I click on slides, slides are very nice but they display only in Firefox. What tool you create for making those nice slides available in the browser?
Thanks

**Comment by huijing** [comment]
Hello, I'm guessing you're referring to my presentation. Those are not really slides per se, they are HTML and CSS, essentially those are web pages which can be viewed in any browser, although the DevTools I am demonstrating are Firefox Devtools. So I guess to answer your question, I use my code editor to write the HTML and CSS for that presentation.

**Comment by eliassal** [comment]
Thanks for the response, they are very nice and well designed and done. I noticed a lot of presentations on your github, do you have any other video sessions related to those presentations?

**Comment by huijing** [comment]
Yes I do. You just gave me the idea that I should link to the available videos on my README file too. Meanwhile, they are all here [https://chenhuijing.com/talks/](https://chenhuijing.com/talks/)

**Comment by eliassal** [comment]
Thanks, great

**Comment by eliassal** [comment]
Chen, I browsed the talks page and was interested of the talk 76-devfestkl-2019, there is some detals but the demos are missing which I am interested in, is it possible to have the demo foiles or the video session if available? Thanks

**Comment by huijing** [comment]
https://huijing.github.io/slides/76-devfestkl-2019/devtools/grid.html
https://huijing.github.io/slides/76-devfestkl-2019/devtools/subgrid.html
Here are the demo files. There was no video recording though.
